### ISSUE TITLE
Feature Request: Send additional parameters to rpc interface

### ISSUE THREAD

**Issue by cdfmr** [baptistecdr/aria2-extensions#104]
Thanks for bringing us the awesome extension.

My Request:
Is it possible to add a new option field for server item to set additional json rpc parameters?
I want create two server items of the same aria2 service, but with different options. For example, one uses the default server options, the other one appends `"all-proxy": "localhost:8080"` option.

**Comment by baptistecdr** [comment]
Your welcome, glad you enjoy it :)

Yeah, I think I can add that, I will look into it. Thanks :)

**Comment by baptistecdr** [comment]
Hello,

I pushed the new version that implement this issue. I hope it worked as expected.
Don't hesitate to report any issue.

Have a nice day. :)

**Comment by cdfmr** [comment]
It works excellently, thank you.
