### ISSUE TITLE
Feature Request: Toggle the 'capture downloads' option with only one click

### ISSUE THREAD

**Issue by cdfmr** [baptistecdr/aria2-extensions#105]
As titled, It should be nice to toggle the 'capture downloads' option with one less click.

Thank you.

**Comment by baptistecdr** [comment]
Hello,

First you need to enable on the server you want to capture the download in the extension preference.
Then, you can enable/disable in the popup, in your server > gear icon, capture downloads.
I don't remember why I put this "limitation", maybe I can modify to be more user friendly.

**Comment by baptistecdr** [comment]
I removed the limitation.
You can quickly enable `capture downloads` on the server that you want in the popup.
