### ISSUE TITLE
Wrong filename on Firefox Extension

### ISSUE THREAD

**Issue by sehang** [baptistecdr/aria2-extensions#106]
I am using Version 3.2.3.

My PC (Windows) IP is: 192.168.1.2
My remote aria2 server (Linux) IP is: 192.168.1.22

I set the "Save files to " from the Settings of Firefox to "C:\Users\user\Downloads".

If I download a file "427012122121.rar". The filename saved in the aria2 server will become "C:\Users\user\Downloads\427012122121.rar". It seems that the filename is combined with the download path of Firefox.

The filename is unable to be recognized in Windows PC because it contains ":" and "\\" characters. E.g.,
https://i.ibb.co/pdqw7Sx/Untitled-1.jpg

Thanks!

**Comment by baptistecdr** [comment]
Hello,

Nice catch, I pushed a fix and you can test it by download the dev version here https://github.com/baptistecdr/aria2-extensions/actions/runs/2237054976

I will push to Firefox Add-ons / Chrome Web Store later.

Thanks :)

**Comment by sehang** [comment]
Hello,

It works. Thanks for your prompt fix.

Thanks a lot! Have a nice day!
