### ISSUE TITLE
Annoying issue: Settings page randomly pops up

### ISSUE THREAD

**Issue by wallace11** [baptistecdr/aria2-extensions#14]
I've got this installed on both Chrome and FF.
This happens mostly when opening the browser for the first time - I'm granted with the settings page of this plugin which was never left open.
Sometimes it just pops out on its own (probably after an update).
If you must keep this behavior for some weird reason, at least let us opt out and disable it.
Thanks!

**Comment by baptistecdr** [comment]
Hello,

I will push an update to suppress this behavior 👍 

Sincerely,
baptistecdr

**Comment by baptistecdr** [comment]
Hello,

I just pushed an update on Firefox and Chrome, It will be available shortly.
See commit https://github.com/baptistecdr/aria2-extensions/commit/c74f5648a27e0fbd38d9f98ff3aec44c30331e0c.
Sorry for the inconvenience about this behavior.

Sincerely,
baptistecdr
