### ISSUE TITLE
v3 unable to connect to remote host

### ISSUE THREAD

**Issue by wallace11** [baptistecdr/aria2-extensions#17]
In the transition to v3 all settings have been removed and I had to set them again.
However, setting them exactly the same way as before, I cannot add new downloads - getting "An error occurred..." message.

- Host is a url on LAN
- Using secret
- Tested on both Firefox & Chrome

**Comment by baptistecdr** [comment]
Hello,

Sorry for the inconvenience, what error do you have in the console ?
You can view in : about:debugging#/runtime/this-firefox Aria2-Integration > Examine.

**Comment by wallace11** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://...

**Comment by baptistecdr** [comment]
Ok, I have chosen to keep the wrong permission in the manifest, I will pushed an update now. 👍

**Comment by baptistecdr** [comment]
Update is available, It should work now. 🤞

**Comment by wallace11** [comment]
I've confirmed that the issue in FF is now solved.
Thanks for the fast response :)
