### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ahmed-tasaly** [baptistecdr/aria2-extensions#19]
the extension is not working on firefox

**Comment by baptistecdr** [comment]
Hello,

I'm sad to hear that... What errors do you get in the toolbox : about:devtools-toolbox?id=baptistecdr%40users.noreply.github.com&type=extension

**Comment by ahmed-tasaly** [comment]
I am so sorry I don't know why it didn't work ,but it do now **thank you**
