### ISSUE TITLE
Does not work on firefox

### ISSUE THREAD

**Issue by SelfishSailfish** [baptistecdr/aria2-extensions#204]
It captured downloads but all tasks failed immediately thereafter.

**Comment by baptistecdr** [comment]
Hello @SelfishSailfish,

* What is your configuration in the extension options ?
* Can you share a link where the problem occur ?
* What are the logs on aria2 ?

I just tested on Firefox using this link: https://proof.ovh.net/files/1Gb.dat, with "Capture Downloads" enabled and without any exclude filters and It works.

**Comment by SelfishSailfish** [comment]
Hi  @baptistecdr 
![image](https://user-images.githubusercontent.com/38479206/198840482-a260eb61-8dfb-4213-943c-a7aa572f3abd.png)

![image](https://user-images.githubusercontent.com/38479206/198840444-23fc5592-d227-4f15-a42a-5eedb2fedff0.png)

**Comment by SelfishSailfish** [comment]
@baptistecdr 
Log file is here

[Aria2.log](https://github.com/baptistecdr/aria2-extensions/files/9894022/Aria2.log)

**Comment by baptistecdr** [comment]
Thanks for the logs, I might know why there is an error.
I will investigate and push a fix, sorry for the inconvenience.

**Comment by baptistecdr** [comment]
Can you try with the upcoming v4 ?

[aria2-integration-4.0.0-firefox.zip](https://github.com/baptistecdr/aria2-extensions/files/9895307/aria2-integration-4.0.0-firefox.zip)

**Comment by SelfishSailfish** [comment]
It works! Thank you so much for your prompt update.

![Screenshot 2022-10-30 232100](https://user-images.githubusercontent.com/38479206/198878215-6c18b7de-ca20-457b-8e26-4da741562df4.png)

**Comment by baptistecdr** [comment]
You can now remove this version and install the one from the Firefox Extension Store.

Thank you for your bug report!
