### ISSUE TITLE
Catch download doesn't work on Chromium 

### ISSUE THREAD

**Issue by wallace11** [baptistecdr/aria2-extensions#21]
Hi there,

Using version 3.0.6 and downloads are not caught - is goes straight to the browser's download manager.

Version 3.x has been plagued with errors in catching downloads. While it did work most of the times with 3.0.2, any interaction with other extensions was not possible (some extensions that trigger downloading).
This functionality used to work flawlessly on v2.x of this plugin.

Please let me know if any additional information is needed.

Thanks.

**Comment by baptistecdr** [comment]
Hello,

Sorry for the inconvenience, I will look into it. In the mean time, do you have an example of links that are not catched ?

**Comment by wallace11** [comment]
Hey

https://speed.hetzner.de
https://archlinuxarm.org/packages/armv7h/ldb ("download" button on the right)

**Comment by wallace11** [comment]
I just confirmed it's working as expected.
Thank you so much :)
