### ISSUE TITLE
[Feature Request] Quickly enable/disable capture downloads

### ISSUE THREAD

**Issue by wallace11** [baptistecdr/aria2-extensions#22]
Hi there :)

While having the capture download on all the time is quite handy, sometimes I stumble upon websites that don't play nice with aria, and then I'm getting a `dl.php` file or something like that, instead of the real file.
When that happens, I usually go to settings and disable capturing just for this single download, and then bring it up again.

I thought it might be useful to have an access to toggling this option through the little popup menu, and potentially even through a custom key binding.

What do you think? :)

Thanks in advance!

**Comment by baptistecdr** [comment]
Hi,

Good idea, I think I will work on that plus fixed the ugly h-scrollbar when there are a lot of tasks.
In the mean time, if you have any idea about the key binding, don't hesitate 👍🏼

**Comment by wallace11** [comment]
Awesome 😎

As for the key binding, I think it should be optional - left blank by
default.

Thanks again for being so responsive.

**Comment by baptistecdr** [comment]
Hello @wallace11,

If you still use the extension, with the new version (4.1.0), you can now use keyboard shortcut to toggle capture downloads. 

Default shortcut is: Ctrl+Maj+D

If you have any problem, don't hesitate to open an issue here: https://github.com/baptistecdr/aria2-integration/issues

Have a nice day,
baptistecdr
