### ISSUE TITLE
The "Exclude File Types" feature has no effect

### ISSUE THREAD

**Issue by m5687946568** [baptistecdr/aria2-extensions#226]
I set "torrent, osz, pdf" and it will still be downloaded via Aria2

![圖片](https://user-images.githubusercontent.com/39809467/205422316-58bbda22-af9f-4e5d-bc84-1d1a8c918ad3.png)

Windows 11 22621.900
Firefox 107.0.1
Aria2 Integration 4.0.3

**Comment by baptistecdr** [comment]
Hello @m5687946568 ,

Thank you for your bug report.

I might have find the issue, I will push an update today.

**Comment by baptistecdr** [comment]
Can you try this version of the extension: https://github.com/baptistecdr/aria2-integration/pull/33 ?

1. Download firefox artifact from https://github.com/baptistecdr/aria2-integration/actions/runs/3608035789
2. Go to about:debugging#/runtime/this-firefox
3. Load a temporary module...
4. Select the zip file

**Comment by m5687946568** [comment]
I tried this version and the functions were just as ineffective.

But I found that the download URL with the extension at the end
It's like https://drivers.amd.com/drivers/amd_chipset_software_4.11.15.342.exe

However, the functionality is not valid for URLs such as
https://bm10.ppy.sh/d/1536761?fs=1536761%20Sano%20Denji%20-%20Taiko%20Time.osz&fd=1536761.osz&ts=1670065754&cs=fc7cb1feec8644a842710b0ffc8e759d&nv=0

https://software.download.prss.microsoft.com/dbazure/Win11_22H2_Chinese_Traditional_x64v1.iso?t=3b12c699-d202-451d-bc7c-0e5fe4f8238b&e=1670152424&h=d8ca4041e3c9984995844c64bd947242e9282fdd020e0ec472e19322d4b6f696

**Comment by baptistecdr** [comment]
I updated the PR, new artifacts: https://github.com/baptistecdr/aria2-integration/actions/runs/3608987074

Look good on my side.

For `https://bm10.ppy.sh/d/1536761?fs=1536761%20Sano%20Denji%20-%20Taiko%20Time.osz&fd=1536761.osz&ts=1670065754&cs=fc7cb1feec8644a842710b0ffc8e759d&nv=0`, I'm not convinced that I should search on the URL's params. You can exclude ppy.sh domain.

**Comment by m5687946568** [comment]
It works with Microsoft Links.

As for other special links,
I had to use the "Exclude Sites" feature.

Thank you for fixing and trying to modify it in time.
