### ISSUE TITLE
火狐直接点击下载，无法获得正确文件名，而且与火狐双重下载

### ISSUE THREAD

**Issue by RallyQ** [baptistecdr/aria2-extensions#23]
您好！这个扩展很好，能分别设置多个RPC端口，谢谢作者！
发现个问题，用【Capture downloads】方式直接点击文件下载，aria2无法获取正确的文件名和扩展名，下载后是一堆字符，如下载这个https://github.com/laurent22/joplin/releases/download/v1.8.5/latest-linux.yml，
得到的文件名是：MjAyMS0wMi0yNyUyRjYwMzlkMDc2ODNmMzcuemlwfFRvbS5hbmQuSmVycnkuMjAyMS5IRFJpcC5YdmlELkFDMy1FVk8uemlwfDE2MjA4MjI1ODJ8OGEzNWNiZjZ8
同时火狐自身也在下载，与aria2双重下载了

而通过右键菜单选择【downloads with aria2】，下载后文件名正常，也没有双重下载问题。
火狐88

**Comment by baptistecdr** [comment]
Hello,

Thank you for your report.
A new version of the extension with a fix is available on Firefox Add-Ons and Chrome Extension Store.

Sincerely,
baptistecdr

**Comment by RallyQ** [comment]
试用了3.09版，仍然不正常。aria2提示目录重复【05/15 16:09:44 [NOTICE] Download GID#6002e41fff669693 not complete: f:/Downsoft/F:/Download/JoplinPortable.exe】

**Comment by RallyQ** [comment]
F:/Download/是火狐中设置的下载目录
f:/Downsoft/是aria2的下载目录
你扩展之前版本没有这个目录问题，3.09版将火狐下载目录跟aria2目录串联用了

**Comment by baptistecdr** [comment]
Hum, I don't understand how to fix it for the moment. 😕
