### ISSUE TITLE
Cookies and Referer Missing

### ISSUE THREAD

**Issue by silver886** [baptistecdr/aria2-extensions#25]
This extension is great, keeps the built-in download popup and integrates Aria2 at the same time.
However, I encountered some problems when downloading folders from Google Drive.

I'm using Firefox 89.0.1 (64-bit) with extension 3.1.4.
When downing folders from Google Drive, if the file is big enough (maybe it takes some time to fetch download information?), the download will be forwarded to Aria2.

For those redirected downloads, from Aria2 log I found that `Referer` and `Cookie` are blank.
```
Referer: about:blank
Cookie:
```
This cause the downloads are always redirected to Google login page.

Please let me know if there is any needed information.

**Comment by baptistecdr** [comment]
Hello,

I will look into it as soon as possible.

**Comment by silver886** [comment]
Here are more results from different website.

❌OneDrive:
```
Referer: <OneDrive URL>
Cookie:
```

❌Visual Studio Subscriptions Portal:
```
Referer: <️Visual Studio URL>
Cookie:
```

It seems like Cookie on Firefox has some trouble . . .



I also tried Brave, a Chromium 92.0.4515.115 (Official Build) (64-bit) based browser, with extension v3.1.4.

❌Google Drive folder:
```
Referer: about:blank
Cookie:
```

✔️OneDrive :
```
Referer: <OneDrive URL>
Cookie: <snip>
```

✔️Visual Studio Subscriptions Portal:
```
Referer: <️Visual Studio URL>
Cookie: <snip>
```

This is minor, it seems like Google Drive folder downloading cannot get the correct Referer.


Please let me know if there's other way to look into this issue that I can help with.

**Comment by baptistecdr** [comment]
Sorry for the delay, I just pushed an update.

For Google Drive, even with cookies downloading from it don't work, I don't know why for the moment.
For OneDrive, it works on Firefox now.
For Visual Studio Subscriptions Portal, I can't try because I dont have a subscription, maybe you have an example, or you can try and tell me.
