### ISSUE TITLE
Exclusion does not work

### ISSUE THREAD

**Issue by SelfishSailfish** [baptistecdr/aria2-extensions#273]
I put pdf in the exclusion input box but it does not work, and my input cannot even be retained in the box if I close the extension options and open it again.

**Comment by baptistecdr** [comment]
Hi @SelfishSailfish ,

Thank you for the feedback.

Sorry for the bug, I will look into it this week end.

Have a nice day,
baptistecdr

**Comment by baptistecdr** [comment]
The exclusion option is correctly saved but there is a bug showing the value, so it should work.

Do you have a PDF's URL example that doesn't work ?

**Comment by baptistecdr** [comment]
Hi @SelfishSailfish ,

Last week-end I pushed an update to fix excludedOptions not showing. Let me know if it's ok on your side.
I modified the code that check if a download have to be captured or not, so give a try but without an example link, it is hard to reproduce and fix.

Have a nice day,
baptistecdr
