### ISSUE TITLE
Support multiple aria2 rpc ?

### ISSUE THREAD

**Issue by abcfy2** [baptistecdr/aria2-extensions#3]
Would you please support multiple aria2 rpc address ?

**Comment by baptistecdr** [comment]
Hello,

Hum, do you mean multiple configuration and when you right click you can choose between Config1, Config2, ConfigN ?

**Comment by abcfy2** [comment]
Yeah. Just like https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjnl

I think it's useful.

**Comment by abcfy2** [comment]
Or like https://addons.mozilla.org/en-US/firefox/addon/aria2-integration/. It will open a window when downloading.

**Comment by baptistecdr** [comment]
Yeah, I think I could work on that.

**Comment by abcfy2** [comment]
Thanks.

**Comment by baptistecdr** [comment]
Oof, 1 year later, I just pushed v3 that include multiple Aria2 server support.
