### ISSUE TITLE
firefox: add support for users who use contextual identities

### ISSUE THREAD

**Issue by S-NA** [baptistecdr/aria2-extensions#304]
When using [Multi-Account Containers](https://github.com/mozilla/multi-account-containers) the incorrect cookies are passed to Aria 2. Ideally the extension would use the `cookieStoreId` property to obtain the correct cookies for the active window/tab.

**Comment by baptistecdr** [comment]
Hello @S-NA ,

Thanks for the issue.
I didn't know about that, I will check and push an update if needed.

have a nice day,
baptistecdr

**Comment by baptistecdr** [comment]
Hello @S-NA ,

A new update is available (v4.2.2), it will now take the correct cookies on Firefox when using Multi-Account Containers !

Thank you again for the feature request ! :)

Have a nice week-end,
baptistecdr
