### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by dream7180** [baptistecdr/aria2-extensions#332]
[messages (zh_CN).json.txt](https://github.com/baptistecdr/aria2-extensions/files/11260087/messages.zh_CN.json.txt)
Could you please add Chinese language into this extension? The lang file has been attached.
One more suggestion, if only one server exists, then the "Downloads with Aria 2" can send the download directly, no need to open a sub-menu.

**Comment by baptistecdr** [comment]
Hi @dream7180 ,

Thank you for your translation and the feature request!

I added in https://github.com/baptistecdr/aria2-integration/pull/135 / https://github.com/baptistecdr/aria2-integration/actions/runs/4735081542?pr=135

Cany you confirm that the translation is correctly loaded?

You are not the only asking for this feature (IIRC) so I removed the sub-menu when there is only one server. :)

Have a nice day,
baptistecdr

**Comment by dream7180** [comment]
Thank you @baptistecdr ,
I have tested the new build with below result:
1. Please rename the Chinese locale folder to **"zh_CN"**, NOT "zh-CN". 
2. ""extensionOptionsTitle" is defined but never used. So "Options" remains English.

**Comment by baptistecdr** [comment]
Thanks for the quick feedback @dream7180 

I updated the PR: https://github.com/baptistecdr/aria2-integration/actions/runs/4742216598?pr=135

**Comment by dream7180** [comment]
Great! Look forward to release updat in Edge extensions store.

**Comment by baptistecdr** [comment]
@dream7180 I sent for review on Edge Store yesterday, so probably end of this week hopefully 🙂
