### ISSUE TITLE
How to enforce dark mode instead of auto?

### ISSUE THREAD

**Issue by uwidev** [baptistecdr/aria2-extensions#384]
My browser (Nightly, aka unbranded Firefox) is set to dark mode, but the extension still appears light. Is there any way to enforce dark mode on the extension?

**Comment by baptistecdr** [comment]
Hello @uwidev ,

Do you have a dark settings on your OS ? Enabling it should enforce Dark Mode.
Enabling Dark theme on Nightly maybe enforce the Dark mode.

I will add an option to select (auto/light/dark) mode.

Have a nice day,
Baptiste C.

**Comment by uwidev** [comment]
Yes, I have my system as dark mode as well as my browser. I have a user.js that does hardening and anti-fingerprint, so it's possible that it's preventing extensions from reading local settings by always defaulting to light. I just tested it on a fresh Firefox/Nightly install, and it properly detects dark mode there.

**Comment by baptistecdr** [comment]
Hello @uwidev,

The feature has been implemented and you can find it in the new version (4.4.0).
In Extension Options > Options > Theme, you can now select Light, Dark or Auto.

Have a nice day,
Baptiste C.
