### ISSUE TITLE
Capture option on Firefox not working

### ISSUE THREAD

**Issue by wallace11** [baptistecdr/aria2-extensions#4]
Exactly what the title says...
Download is not captured. Tested with https://www.thinkbroadband.com/download
Works fine from context menu.

**Comment by baptistecdr** [comment]
Hello,

That's odd, any download is captured on my computer.

What's your configuration in (Aria2 Integration -> Preferences) ?
What errors do you have in about:debugging#/runtime/this-firefox -> Aria2c Integration -> Inspect when you try to capture a download ?

**Comment by wallace11** [comment]
Here's my config:
![image](https://user-images.githubusercontent.com/5497761/74182196-f26fdc80-4c85-11ea-9409-5025bc6c5acc.png)

Inspection doesn't reveal anything... Errors don't change when I try to download
![image](https://user-images.githubusercontent.com/5497761/74182382-48448480-4c86-11ea-96c7-265cb3fc475e.png)

I'm running FF 72.0.2 on Arch Linux

**Comment by wallace11** [comment]
It took me time to realize that my FF settings for auto-download (without showing the "save file" prompt) is not the same as is Chrome, which doesn't prompt for anything.
Apparently all I had to do was to simply click "Save File" and it was captured as intended.

I'm extremely sorry for the false alarm there...
I need to find a way to completely disable this prompt :unamused:
