### ISSUE TITLE
Change download location path ?

### ISSUE THREAD

**Issue by nhathoang24** [baptistecdr/aria2-extensions#597]
Hi,
I want to change download location path to C:\Users\hoang\Downloads put it always download to same folder with aria2.exe, do you have any help ?
Thank you

**Comment by baptistecdr** [comment]
Hello,
In RPC Paramaters, just put:

dir: C:\Users\hoang\Downloads

Let me know if it works

**Comment by nhathoang24** [comment]
It work, thank you so much !

**Comment by nhathoang24** [comment]
It work, thank you so much !
