### ISSUE TITLE
Ability to rename files before download

### ISSUE THREAD

**Issue by gbcox** [baptistecdr/aria2-extensions#7]
When selecting from context menu, no option to rename file.  

When using built in Fx dialog, to save as, rename is accepted, but Fx cancels download, routes to 
plugin, but plugin doesn't process the rename, just downloads using original name.

**Comment by baptistecdr** [comment]
Hello,

Thank you for your issue and sorry for the delay, I just pushed an update with this commit [0db0629](https://github.com/baptistecdr/aria2-extensions/commit/d5f8caaf959a0640bb4385b7bece473215f77874).
Hope it works as expected. 🙂

Best regards,
baptistecdr

**Comment by gbcox** [comment]
Works on multiple websites with multiple download methods.  Thanks!
